version: '3.8'

services:
  app:
    build: .
    container_name: sesi-14
    restart: always
    environment:
      - JWT_SECRET=rahasia
      - DB_HOST=db
      - DB_NAME=todos
      - DB_USER=ruditopra
      - DB_PASS=1234
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ruditopra
      POSTGRES_PASSWORD: 1234